### ISSUE TITLE
gtk/gtkpagesetupunixdialog.h not exist

### ISSUE THREAD

**Issue by longlene** [coregtk/coregtk#5]
I use clang-3.4, libobjc, cocotron and gtk-2,24.23 to compile coregtk on my Funtoo Linux.
and encountered a problem:
gtk/gtkpagesetupunixdialog.h included by CGTKPageSetupUnixDialog., but on my Funtoo Linux it not exist

**Comment by tylerburton** [comment]
Issue is no longer applicable to new version.
